import { exportEnvRecord, writeExportedEnv } from "../envExporter";
import { EnvRecord } from "../envParser.types";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";

const sampleRecord: EnvRecord = {
  DATABASE_URL: "postgres://localhost:5432/db",
  API_KEY: "abc123",
  APP_NAME: "my app with spaces",
};

describe("exportEnvRecord", () => {
  it("exports as dotenv format by default", () => {
    const result = exportEnvRecord(sampleRecord);
    expect(result).toContain("DATABASE_URL=postgres://localhost:5432/db");
    expect(result).toContain("API_KEY=abc123");
    expect(result).toContain('APP_NAME="my app with spaces"');
  });

  it("includes a comment header in dotenv format when includeComments is true", () => {
    const result = exportEnvRecord(sampleRecord, { format: "dotenv", includeComments: true });
    expect(result).toMatch(/^# Generated by envoy-cli/);
  });

  it("omits comment header when includeComments is false", () => {
    const result = exportEnvRecord(sampleRecord, { format: "dotenv", includeComments: false });
    expect(result).not.toContain("# Generated");
  });

  it("exports as JSON format", () => {
    const result = exportEnvRecord(sampleRecord, { format: "json" });
    const parsed = JSON.parse(result);
    expect(parsed).toEqual(sampleRecord);
  });

  it("exports as shell format", () => {
    const result = exportEnvRecord(sampleRecord, { format: "shell" });
    expect(result).toContain("export DATABASE_URL='postgres://localhost:5432/db'");
    expect(result).toContain("export API_KEY='abc123'");
  });

  it("throws on unsupported format", () => {
    expect(() =>
      exportEnvRecord(sampleRecord, { format: "xml" as any })
    ).toThrow("Unsupported export format: xml");
  });
});

describe("writeExportedEnv", () => {
  it("writes dotenv content to a file", () => {
    const tmpFile = path.join(os.tmpdir(), `envoy-test-${Date.now()}.env`);
    writeExportedEnv(sampleRecord, { outputPath: tmpFile, includeComments: false });
    const content = fs.readFileSync(tmpFile, "utf-8");
    expect(content).toContain("API_KEY=abc123");
    fs.unlinkSync(tmpFile);
  });

  it("writes JSON content to a file", () => {
    const tmpFile = path.join(os.tmpdir(), `envoy-test-${Date.now()}.json`);
    writeExportedEnv(sampleRecord, { outputPath: tmpFile, format: "json" });
    const content = fs.readFileSync(tmpFile, "utf-8");
    expect(JSON.parse(content)).toEqual(sampleRecord);
    fs.unlinkSync(tmpFile);
  });
});
