import * as fs from "fs";
import * as path from "path";
import { EnvRecord } from "./envParser.types";

export type ExportFormat = "dotenv" | "json" | "shell";

export interface ExportOptions {
  format?: ExportFormat;
  outputPath?: string;
  includeComments?: boolean;
}

export function exportEnvRecord(
  record: EnvRecord,
  options: ExportOptions = {}
): string {
  const { format = "dotenv", includeComments = true } = options;

  switch (format) {
    case "dotenv":
      return exportAsDotenv(record, includeComments);
    case "json":
      return exportAsJson(record);
    case "shell":
      return exportAsShell(record);
    default:
      throw new Error(`Unsupported export format: ${format}`);
  }
}

export function writeExportedEnv(
  record: EnvRecord,
  options: ExportOptions = {}
): void {
  const { outputPath = ".env", format = "dotenv" } = options;
  const content = exportEnvRecord(record, options);
  const resolved = path.resolve(outputPath);
  fs.writeFileSync(resolved, content, "utf-8");
}

function exportAsDotenv(record: EnvRecord, includeComments: boolean): string {
  const header = includeComments
    ? `# Generated by envoy-cli on ${new Date().toISOString()}\n`
    : "";
  const lines = Object.entries(record).map(([key, value]) => {
    const needsQuotes = /\s|#|"/.test(value);
    const formatted = needsQuotes ? `"${value.replace(/"/g, '\\"')}"` : value;
    return `${key}=${formatted}`;
  });
  return header + lines.join("\n") + "\n";
}

function exportAsJson(record: EnvRecord): string {
  return JSON.stringify(record, null, 2) + "\n";
}

function exportAsShell(record: EnvRecord): string {
  const lines = Object.entries(record).map(([key, value]) => {
    const escaped = value.replace(/'/g, "'\\''" );
    return `export ${key}='${escaped}'`;
  });
  return lines.join("\n") + "\n";
}
